Repository goorm-debug-alss/petclinic, pull requests merged in 2024-12, with the labels that each got.

#4 refactor: entity 수정 및 추가
  src/main/java/org/springframework/samples/petclinic/PetClinicRuntimeHints.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/model/Appointment.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/model/enums/ApptStatus.java
  src/main/java/org/springframework/samples/petclinic/domain/history/model/History.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/Owner.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/OwnerRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/Visit.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/VisitController.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/model/Owner.java
  src/main/java/org/springframework/samples/petclinic/domain/pet/PetController.java
  src/main/java/org/springframework/samples/petclinic/domain/pet/PetTypeFormatter.java
  src/main/java/org/springframework/samples/petclinic/domain/pet/PetValidator.java
  src/main/java/org/springframework/samples/petclinic/domain/pet/model/Pet.java
  src/main/java/org/springframework/samples/petclinic/domain/pet/model/PetType.java
  src/main/java/org/springframework/samples/petclinic/domain/review/model/Review.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/Specialty.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/Vet.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/VetController.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/VetRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/model/Specialty.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/model/Vet.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/model/VetSpecialty.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/VisitController.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/model/Visit.java
  src/main/resources/application.properties
Labels: refactoring

#9 feat : 예약 생성 API 구현
  build.gradle
  src/main/java/org/springframework/samples/petclinic/domain/appointment/controller/AppointmentController.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/AppointmentRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/AppointmentResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/garbage/GarbagePetRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/garbage/GarbageVetRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/model/Appointment.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/repository/AppointmentRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java
  src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java
Labels: feat, refactoring, chore

#13 refactor : 예약 생성 API 리팩토링
  src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/AppointmentRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/AppointmentResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/Result.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/StatusCode.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java
  src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java
Labels: feat, refactoring

#14 feat: 수의사 등록 기능 추가(#6)
  src/main/java/org/springframework/samples/petclinic/domain/vet/VetController.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/VetRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/VetSpecialityRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/controller/VetController.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/controller/dto/VetRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/controller/dto/VetResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/convert/VetConvert.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/model/Vet.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/model/VetSpecialty.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/service/VetService.java
  src/main/java/org/springframework/samples/petclinic/speciality/SpecialityRepository.java
  src/main/java/org/springframework/samples/petclinic/speciality/dto/SpecialityRequestDto.java
  src/main/java/org/springframework/samples/petclinic/speciality/model/Specialty.java
  src/main/java/org/springframework/samples/petclinic/speciality/service/SpecialityService.java
Labels: feat

#20 feat: 수의사 조회 기능 추가(#8)
  src/main/java/org/springframework/samples/petclinic/domain/vet/VetRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/controller/VetController.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/model/Vet.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/model/VetSpecialty.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/service/VetService.java
Labels: feat

#23 feat: 수의사 수정 / 삭제 기능 구현 (#21)
  src/main/java/org/springframework/samples/petclinic/domain/vet/VetSpecialityRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/controller/VetController.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/service/VetService.java
Labels: feat

#27 feat: 로그인, 회원가입 기능 추가
  build.gradle
  src/main/java/org/springframework/samples/petclinic/config/web/WebConfig.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/OwnerRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/controller/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/dto/LoginRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/dto/RegisterRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/repository/OwnerRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerService.java
  src/main/java/org/springframework/samples/petclinic/domain/token/Interface/TokenHelperInterface.java
  src/main/java/org/springframework/samples/petclinic/domain/token/dto/TokenDto.java
  src/main/java/org/springframework/samples/petclinic/domain/token/dto/TokenResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/token/helper/JwtTokenHelper.java
  src/main/java/org/springframework/samples/petclinic/domain/token/service/TokenService.java
  src/main/java/org/springframework/samples/petclinic/interceptor/AuthorizationInterceptor.java
  src/main/resources/application.properties
Labels: feat, refactoring

#29 feat : 예약 수정 / 삭제 API 기능 추가(#24)
  src/main/java/org/springframework/samples/petclinic/domain/appointment/controller/AppointmentController.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/model/Appointment.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/repository/AppointmentRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentDeleteService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentReadService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentUpdateService.java
  src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java
  src/test/java/domain/appointment/service/AppointmentDeleteServiceTest.java
  src/test/java/domain/appointment/service/AppointmentReadServiceTest.java
  src/test/java/domain/appointment/service/AppointmentUpdateServiceTest.java
Labels: feat, refactoring

#32 feat: 분야별 수의사 조회 기능 추가 (#25)
  src/main/java/org/springframework/samples/petclinic/domain/vet/VetRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/VetSpecialityRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/controller/VetController.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/service/VetService.java
Labels: feat

#30 feat: 방문내역 생성, 조회 API 기능 추가
  src/main/java/org/springframework/samples/petclinic/domain/visit/VisitController.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/controller/VisitController.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/dto/VisitRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/dto/VisitResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/enums/StatusCode.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/model/Visit.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/repository/VisitRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/service/VisitService.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/tempRepository/TempPetRepository.java
Labels: feat

#35 feat: 주인 정보 수정 API 추가
  src/main/java/org/springframework/samples/petclinic/domain/owner/controller/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/dto/UpdatePasswordRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/dto/UpdateProfileRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/repository/OwnerRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerService.java
Labels: feat

#42 refactor : 예약 날짜 LocalDate -> LocalDateTime으로 변경(#33)
  src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/AppointmentRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/AppointmentResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/model/Appointment.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentReadService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentUpdateService.java
  src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java
  src/test/java/domain/appointment/service/AppointmentReadServiceTest.java
  src/test/java/domain/appointment/service/AppointmentUpdateServiceTest.java
Labels: feat, refactoring

#48 feat: 진료내역 생성, 조회 API 기능 추가, TempPetRepository 삭제
  src/main/java/org/springframework/samples/petclinic/domain/history/controller/HistoryController.java
  src/main/java/org/springframework/samples/petclinic/domain/history/dto/HistoryRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/history/dto/HistoryResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/history/enums/StatusCode.java
  src/main/java/org/springframework/samples/petclinic/domain/history/repository/HistoryRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/history/service/HistoryService.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/service/VisitService.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/tempRepository/TempPetRepository.java
Labels: feat, refactoring

#53 refactor: 테스트용 Repository 삭제후 사용코드 리팩토링(#44)
  src/main/java/org/springframework/samples/petclinic/domain/appointment/garbage/GarbagePetRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/garbage/GarbageVetRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentUpdateService.java
  src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java
  src/test/java/domain/appointment/service/AppointmentUpdateServiceTest.java
Labels: feat, refactoring

#54 feat: 진료내역 수정/삭제 기능 구현(#51)
  src/main/java/org/springframework/samples/petclinic/domain/history/controller/HistoryController.java
  src/main/java/org/springframework/samples/petclinic/domain/history/service/HistoryService.java
Labels: feat

#58 feat: VetService Register 메서드 null 처리 (#56)
  src/main/java/org/springframework/samples/petclinic/domain/vet/controller/dto/VetRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/service/VetService.java
  src/test/java/domain/vet/controller/VetControllerTest.java
  src/test/java/domain/vet/service/VetServiceTest.java
Labels: fix

#60 refactor: 예약 API 리팩토링 및 수정(#57)
  src/main/java/org/springframework/samples/petclinic/domain/appointment/controller/AppointmentController.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/mapper/AppointmentHelper.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentDeleteService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentReadService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentUpdateService.java
  src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java
  src/test/java/domain/appointment/service/AppointmentDeleteServiceTest.java
  src/test/java/domain/appointment/service/AppointmentReadServiceTest.java
Labels: feat, refactoring

#62 fix: Vet delete 디버깅 (#59)
  src/main/java/org/springframework/samples/petclinic/domain/vet/VetRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/controller/VetController.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/service/VetService.java
  src/test/java/domain/vet/controller/VetControllerTest.java
  src/test/java/domain/vet/service/VetServiceTest.java
Labels: fix

#64 feat: 후기 기능 API 기능 구현 및 테스트 작성
  src/main/java/org/springframework/samples/petclinic/domain/review/controller/ReviewController.java
  src/main/java/org/springframework/samples/petclinic/domain/review/dto/Result.java
  src/main/java/org/springframework/samples/petclinic/domain/review/dto/ReviewRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/review/dto/ReviewResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/review/dto/StatusCode.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/OwnerNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/ReviewNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/ReviewOwnershipException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/VetNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/mapper/ReviewHelper.java
  src/main/java/org/springframework/samples/petclinic/domain/review/model/Review.java
  src/main/java/org/springframework/samples/petclinic/domain/review/repository/ReviewRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewCreateService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewDeleteService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewReadService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewUpdateService.java
  src/main/java/org/springframework/samples/petclinic/interceptor/AuthorizationInterceptor.java
  src/test/java/domain/review/service/ReviewCreateServiceTest.java
  src/test/java/domain/review/service/ReviewDeleteServiceTest.java
  src/test/java/domain/review/service/ReviewReadServiceTest.java
  src/test/java/domain/review/service/ReviewUpdateServiceTest.java
Labels: feat, refactoring

#67 feat: 예약 API 테스트 케이스 추가 및 수정(#66)
  src/main/java/org/springframework/samples/petclinic/domain/review/controller/ReviewController.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/InvalidContentException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/InvalidScoreException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewCreateService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewReadService.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/model/Vet.java
  src/test/java/domain/review/service/ReviewCreateServiceTest.java
  src/test/java/domain/review/service/ReviewReadServiceTest.java
Labels: feat, refactoring

#69 feat: 방문 생성,조회 API 테스트코드 작성(#68)
  src/main/java/org/springframework/samples/petclinic/domain/visit/controller/VisitController.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/dto/VisitRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/dto/VisitResponseDto.java
  src/test/java/domain/visit/controller/VisitControllerTest.java
  src/test/java/domain/visit/service/VisitServiceTest.java
Labels: feat, refactoring

#71 refactor: 주인 API 리팩토링(#65)
  src/main/java/org/springframework/samples/petclinic/domain/owner/controller/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/exception/InvalidPasswordException.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/exception/OwnerNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/model/Owner.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerAuthService.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerProfileService.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerReadService.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerService.java
Labels: feat, refactoring

#73 feat: 비밀번호 암호화 구현(#72)
  build.gradle
  src/main/java/org/springframework/samples/petclinic/config/security/JwtAuthenticationFilter.java
  src/main/java/org/springframework/samples/petclinic/config/security/SecurityConfig.java
  src/main/java/org/springframework/samples/petclinic/config/security/TokenBasedAuthentication.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerAuthService.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerProfileService.java
Labels: feat

#79 feat: 주인 서비스, 토큰 서비스 테스트 구현(#76)
  src/test/java/domain/owner/service/BlacklistServiceTest.java
  src/test/java/domain/owner/service/OwnerAuthServiceTest.java
  src/test/java/domain/owner/service/OwnerProfileServiceTest.java
  src/test/java/domain/owner/service/OwnerReadServiceTest.java
  src/test/java/domain/token/service/TokenServiceTest.java
Labels: feat

#89 refactor: 예약 API 응답 수정 및 리팩토링(#87)
  src/main/java/org/springframework/samples/petclinic/domain/appointment/controller/AppointmentController.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/AppointmentResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/Result.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/ResultResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/StatusCode.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/exception/PetNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/exception/VetNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/mapper/AppointmentHelper.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentDeleteService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentReadService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentUpdateService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/EntityRetrievalService.java
  src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java
  src/test/java/domain/appointment/service/AppointmentDeleteServiceTest.java
  src/test/java/domain/appointment/service/AppointmentReadServiceTest.java
  src/test/java/domain/appointment/service/AppointmentUpdateServiceTest.java
Labels: feat, refactoring

#90 refactor: 리뷰 API 응답 수정 및 리팩토링(#88)
  src/main/java/org/springframework/samples/petclinic/domain/review/dto/Result.java
  src/main/java/org/springframework/samples/petclinic/domain/review/dto/ReviewResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/review/dto/StatusCode.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/OwnerNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/ReviewIdNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/ReviewOwnershipException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/VetNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/mapper/ReviewHelper.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewCreateService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewDeleteService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewEntityRetrievalService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewReadService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewUpdateService.java
  src/test/java/domain/review/service/ReviewCreateServiceTest.java
  src/test/java/domain/review/service/ReviewDeleteServiceTest.java
  src/test/java/domain/review/service/ReviewReadServiceTest.java
  src/test/java/domain/review/service/ReviewUpdateServiceTest.java
Labels: feat, refactoring

#94 refactor: 주석 제거, 클래스명 변경, 메서드 추출로 가독성 향상(#91)
  src/main/java/org/springframework/samples/petclinic/domain/appointment/controller/AppointmentController.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/exception/AppointmentNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/exception/PetNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/exception/VetNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/mapper/AppointmentHelper.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentDeleteService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentEntityRetrievalService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentReadService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentUpdateService.java
  src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java
  src/test/java/domain/appointment/service/AppointmentDeleteServiceTest.java
  src/test/java/domain/appointment/service/AppointmentReadServiceTest.java
  src/test/java/domain/appointment/service/AppointmentUpdateServiceTest.java
Labels: refactoring, style

#95 refactor: 주석 제거 및 메소드 추출(#92)
  src/main/java/org/springframework/samples/petclinic/domain/review/controller/ReviewController.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewCreateService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewDeleteService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewEntityRetrievalService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewReadService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewUpdateService.java
Labels: refactoring, style

#98 refactor: 수의사 controller 테스트 수정 (#86)
  src/test/java/domain/vet/controller/VetControllerTest.java
  src/test/java/domain/vet/service/VetServiceTest.java
Labels: refactoring

#103 feat: Vet 관련 CustomException 처리 (#102)
  src/main/java/org/springframework/samples/petclinic/common/error/VetErrorCode.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/controller/VetController.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/service/VetService.java
Labels: feat, refactoring

#107 refactor: 예약 API 리팩토링 및 통합 테스트 구현(#101)
  build.gradle
  src/main/java/org/springframework/samples/petclinic/common/error/AppointmentErrorCode.java
  src/main/java/org/springframework/samples/petclinic/common/error/PetErrorCode.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/controller/AppointmentController.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/AppointmentRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/dto/AppointmentResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/exception/AppointmentNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/exception/PetNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/exception/VetNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/mapper/AppointmentHelper.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/mapper/AppointmentMapper.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/model/Appointment.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/repository/AppointmentRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentCreateService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentEntityRetrievalService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentReadService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/AppointmentUpdateService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/CreateAppointmentService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/DeleteAppointmentService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/ReadAppointmentService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/UpdateAppointmentService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewEntityRetrievalService.java
  src/test/java/domain/appointment/controller/AppointmentControllerTest.java
  src/test/java/domain/appointment/service/AppointmentCreateServiceTest.java
  src/test/java/domain/appointment/service/AppointmentDeleteServiceTest.java
  src/test/java/domain/appointment/service/AppointmentReadServiceTest.java
  src/test/java/domain/appointment/service/AppointmentUpdateServiceTest.java
  src/test/java/domain/appointment/service/CreateAppointmentServiceTest.java
  src/test/java/domain/appointment/service/DeleteAppointmentServiceTest.java
  src/test/java/domain/appointment/service/ReadAppointmentServiceTest.java
  src/test/java/domain/appointment/service/UpdateAppointmentServiceTest.java
Labels: feat, refactoring
