Repository goorm-debug-alss/petclinic, pull requests merged in 2025-01, with the labels that each got.

#110 refactor: 리뷰 API 리팩토링 및 통합 테스트 구현(#108)
  src/main/java/org/springframework/samples/petclinic/common/error/OwnerErrorCode.java
  src/main/java/org/springframework/samples/petclinic/common/error/ReviewErrorCode.java
  src/main/java/org/springframework/samples/petclinic/domain/review/controller/ReviewController.java
  src/main/java/org/springframework/samples/petclinic/domain/review/dto/ReviewRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/review/dto/ReviewResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/InvalidContentException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/InvalidScoreException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/OwnerNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/ReviewIdNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/ReviewNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/ReviewOwnershipException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/exception/VetNotFoundException.java
  src/main/java/org/springframework/samples/petclinic/domain/review/mapper/ReviewMapper.java
  src/main/java/org/springframework/samples/petclinic/domain/review/model/Review.java
  src/main/java/org/springframework/samples/petclinic/domain/review/repository/ReviewRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/CreateReviewService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/DeleteReviewService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReadReviewService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewCreateService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewDeleteService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewEntityRetrievalService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewReadService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewUpdateService.java
  src/main/java/org/springframework/samples/petclinic/domain/review/service/UpdateReviewService.java
  src/test/java/domain/appointment/controller/AppointmentControllerTest.java
  src/test/java/domain/appointment/service/CreateAppointmentServiceTest.java
  src/test/java/domain/appointment/service/UpdateAppointmentServiceTest.java
  src/test/java/domain/review/controller/ReviewControllerTest.java
  src/test/java/domain/review/service/CreateReviewServiceTest.java
  src/test/java/domain/review/service/DeleteReviewServiceTest.java
  src/test/java/domain/review/service/ReadReviewServiceTest.java
  src/test/java/domain/review/service/ReviewCreateServiceTest.java
  src/test/java/domain/review/service/ReviewDeleteServiceTest.java
  src/test/java/domain/review/service/ReviewReadServiceTest.java
  src/test/java/domain/review/service/ReviewUpdateServiceTest.java
  src/test/java/domain/review/service/UpdateReviewServiceTest.java
Labels: feat, refactoring

#109 refactor: 방문 관련 API 응답 수정 및 리팩토링(#105)
  src/main/java/org/springframework/samples/petclinic/common/error/VisitErrorCode.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/controller/VisitController.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/dto/VisitResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/service/VisitService.java
  src/test/java/domain/visit/controller/VisitControllerTest.java
  src/test/java/domain/visit/service/VisitServiceTest.java
Labels: feat, refactoring, docs

#112 refactor: Vet 관련 리팩토링 (#104)
  src/main/java/org/springframework/samples/petclinic/common/error/SpecialityErrorCode.java
  src/main/java/org/springframework/samples/petclinic/domain/speciality/dto/SpecialityRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/speciality/service/SpecialityService.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/SpecialityRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/VetSpecialityRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/VetSpecialtyRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/controller/dto/VetRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/controller/dto/VetResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/convert/VetConvert.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/convert/VetSpecialtyConvert.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/model/Specialty.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/model/VetSpeciality.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/service/SpecialityService.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/service/VetService.java
  src/test/java/domain/vet/controller/VetControllerTest.java
  src/test/java/domain/vet/service/VetServiceTest.java
Labels: refactoring

#114 refactor: 방문 관련 API 응답 수정 및 리팩토링(#106)
  src/main/java/org/springframework/samples/petclinic/common/error/HistoryErrorCode.java
  src/main/java/org/springframework/samples/petclinic/domain/history/controller/HistoryController.java
  src/main/java/org/springframework/samples/petclinic/domain/history/dto/HistoryResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/history/service/HistoryService.java
  src/test/java/domain/history/controller/HistoryControllerTest.java
  src/test/java/domain/history/service/HistoryServiceTest.java
  src/test/java/domain/visit/service/VisitServiceTest.java
Labels: feat, refactoring, docs

#117 feat: vet 통합 테스트 구현 (#113)
  src/main/java/org/springframework/samples/petclinic/domain/vet/controller/VetController.java
  src/main/resources/application-test.properties
  src/main/resources/db/mysql/data.sql
  src/main/resources/db/mysql/schema.sql
  src/test/java/domain/vet/service/VetServiceIntegrationTest.java
  src/test/java/domain/vet/service/VetServiceTest.java
Labels: feat

#120 feat: 커스텀 예외 구현, 테스트코드 수정 (#115)
  src/main/java/org/springframework/samples/petclinic/common/error/PetErrorCode.java
  src/main/java/org/springframework/samples/petclinic/domain/pet/service/PetService.java
  src/test/java/domain/pet/controller/PetControllerTest.java
  src/test/java/domain/pet/service/PetServiceTest.java
Labels: feat, refactoring

#123 refactor: 방문/진료내역 API 리팩토링 및 테스트케이스 추가(#116)
  src/main/java/org/springframework/samples/petclinic/domain/history/controller/HistoryController.java
  src/main/java/org/springframework/samples/petclinic/domain/history/dto/HistoryRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/history/enums/StatusCode.java
  src/main/java/org/springframework/samples/petclinic/domain/history/service/HistoryService.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/controller/VisitController.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/dto/VisitRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/enums/StatusCode.java
  src/main/java/org/springframework/samples/petclinic/handler/GlobalExceptionHandler.java
  src/test/java/domain/history/service/HistoryServiceTest.java
Labels: feat, refactoring

#125 refactor: 주인 API 리팩토링(#111)
  src/main/java/org/springframework/samples/petclinic/common/error/OwnerErrorCode.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/controller/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/dto/LoginRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/dto/OwnerResponseDto.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/dto/RegisterRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/dto/UpdatePasswordRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/dto/UpdateProfileRequestDto.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/mapper/OwnerMapper.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerAuthService.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerProfileService.java
  src/main/java/org/springframework/samples/petclinic/domain/owner/service/OwnerReadService.java
  src/test/java/domain/appointment/controller/AppointmentControllerTest.java
  src/test/java/domain/owner/controller/OwnerControllerTest.java
  src/test/java/domain/owner/service/OwnerAuthServiceTest.java
  src/test/java/domain/owner/service/OwnerProfileServiceTest.java
  src/test/java/domain/owner/service/OwnerReadServiceTest.java
Labels: feat, refactoring

#128 refactor: VetControllerTest 수정 (#127)
  src/test/java/domain/vet/controller/VetControllerTest.java
Labels: refactoring

#129 docs: 프로젝트 README.md 작성(#126)
  README.md
Labels: docs

#131 fix: 배포 빌드시 ProcessAOT 오류가 발생하여 build.gradle에서 AOT 관련 플러그인 주석 처리하여 오류 해결
  build.gradle
Labels: fix

#132 feat: 방문/진료내역 통합테스트 구현
  src/test/java/domain/history/service/HistoryServiceIntegrationTest.java
  src/test/java/domain/visit/service/VisitServiceIntegrationTest.java
Labels: feat

#140 debug: Pet 삭제 시 관련 테이블로 인한 삭제 불가 수정(#139)
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/CreateAppointmentService.java
  src/main/java/org/springframework/samples/petclinic/domain/appointment/service/UpdateAppointmentService.java
  src/main/java/org/springframework/samples/petclinic/domain/history/repository/HistoryRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/history/service/HistoryService.java
  src/main/java/org/springframework/samples/petclinic/domain/pet/enums/PetStatus.java
  src/main/java/org/springframework/samples/petclinic/domain/pet/mapper/PetMapper.java
  src/main/java/org/springframework/samples/petclinic/domain/pet/model/Pet.java
  src/main/java/org/springframework/samples/petclinic/domain/pet/repository/PetRepository.java
  src/main/java/org/springframework/samples/petclinic/domain/pet/service/PetService.java
  src/main/java/org/springframework/samples/petclinic/domain/vet/model/Vet.java
  src/main/java/org/springframework/samples/petclinic/domain/visit/service/VisitService.java
  src/main/resources/db/mysql/data.sql
  src/main/resources/db/mysql/schema.sql
  src/test/java/domain/appointment/service/CreateAppointmentServiceTest.java
  src/test/java/domain/history/service/HistoryServiceIntegrationTest.java
  src/test/java/domain/history/service/HistoryServiceTest.java
  src/test/java/domain/owner/controller/OwnerControllerTest.java
  src/test/java/domain/pet/service/PetServiceTest.java
  src/test/java/domain/review/controller/ReviewControllerTest.java
  src/test/java/domain/review/service/DeleteReviewServiceTest.java
  src/test/java/domain/review/service/ReadReviewServiceTest.java
  src/test/java/domain/vet/controller/VetControllerTest.java
  src/test/java/domain/vet/service/VetServiceTest.java
  src/test/java/domain/visit/service/VisitServiceTest.java
Labels: fix, refactoring
